Repository paion-data/nexusgraph, pull requests merged in 2023-08, with the labels that each got.

#133 Implementation packages refactoring
  docs/docs/development/architecture.md
  docs/docs/development/img/nexusgraph-separation-of-concerns .drawio
  docs/docs/development/img/nexusgraph-separation-of-concerns.png
  docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/development/architecture.md
  docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/development/img/nexusgraph-separation-of-concerns .drawio
  docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/development/img/nexusgraph-separation-of-concerns.png
  packages/nexusgraph-app/src/App.tsx
  packages/nexusgraph-app/src/index.tsx
  packages/nexusgraph-editor/src/Lexical/plugins/NexusgraphOnChangePlugin.test.tsx
  packages/nexusgraph-editor/src/Lexical/plugins/NexusgraphOnChangePlugin.tsx
  packages/nexusgraph-editor/src/Lexical/plugins/ToolbarPlugin.test.tsx
  packages/nexusgraph-editor/src/Lexical/processor/RemoteNaturalLanguageProcessor.test.ts
  packages/nexusgraph-editor/src/Lexical/processor/RemoteNaturalLanguageProcessor.ts
  packages/nexusgraph-graph/index.ts
  packages/nexusgraph-graph/src/Graph.tsx
  packages/nexusgraph-graph/src/GraphVisualizer.tsx
  packages/nexusgraph-graph/src/VisualizationView.test.ts
  packages/nexusgraph-graph/src/VisualizationView.tsx
  packages/nexusgraph-graph/src/basicTypes.ts
  packages/nexusgraph-graph/src/event-handler/GraphEventHandlerModel.ts
  packages/nexusgraph-graph/src/processor/NodesExpand.ts
  packages/nexusgraph-graph/src/shared/editor/editorDuck.ts
  packages/nexusgraph-graph/src/shared/globalState.ts
  packages/nexusgraph-graph/src/shared/rootReducer.ts
  packages/nexusgraph-nlp/src/processor/NaturalLanguageProcessor.ts
  packages/nexusgraph-nlp/src/processor/RemoteNaturalLanguageProcessor.test.ts
  packages/nexusgraph-nlp/src/processor/RemoteNaturalLanguageProcessor.ts
  packages/nexusgraph-provider/index.ts
  packages/nexusgraph-provider/package.json
  packages/nexusgraph-provider/src/StoreProvider.tsx
  packages/nexusgraph-provider/src/editorLine/editorLineDuck.test.ts
  packages/nexusgraph-provider/src/editorLine/editorLineDuck.ts
  packages/nexusgraph-provider/src/globalState.ts
  packages/nexusgraph-provider/src/nlp/nlpDuck.test.ts
  packages/nexusgraph-provider/src/nlp/nlpDuck.ts
  packages/nexusgraph-provider/src/rootReducer.ts
  packages/nexusgraph-provider/src/types.ts
Labels: MERGEABLE

#141 turn off duplicate checking for two files
  .sonarcloud.properties
Labels: MERGEABLE

#147 Add heading to level-six
  cypress/e2e/editor.spec.cy.ts
  packages/nexusgraph-editor/src/Lexical/plugins/ToolbarPlugin.tsx
  packages/nexusgraph-editor/src/Lexical/plugins/styled.ts
  packages/nexusgraph-editor/src/Lexical/themes/ExampleTheme.js
Labels: MERGEABLE

#148 Adjust app margin
  packages/nexusgraph-app/src/styled.ts
Labels: MERGEABLE

#142 Implement login page
  .github/workflows/ci-cd.yml
  cypress.config.ts
  cypress/e2e/0.login.spec.cy.ts
  cypress/e2e/NodeInspectorPanel.spec.cy.ts
  cypress/e2e/editor.spec.cy.ts
  cypress/e2e/nexusgraph.spec.cy.ts
  cypress/support/commands.ts
  cypress/support/global.d.ts
  docs/docs/development/environment.md
  package.json
  packages/nexusgraph-app/package.json
  packages/nexusgraph-app/src/App.tsx
  packages/nexusgraph-app/src/LogtoProvider.tsx
  packages/nexusgraph-app/src/index.tsx
  tsconfig.json
  yarn.lock
Labels: BREAKING CHANGE, NEW FEATURE

#146 Logo transform to svg format
  config/webpack/webpack.config.js
  docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/development/img/nexusgraph-architecture.drawio
  docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/development/img/nexusgraph-architecture.png
  package.json
  packages/nexusgraph-app/public/app-logo.ai
  packages/nexusgraph-app/public/app-logo.png
  packages/nexusgraph-app/public/app-logo.svg
  packages/nexusgraph-app/src/App.tsx
  packages/nexusgraph-app/src/styled.ts
  packages/nexusgraph-graph/src/custom.d.ts
  yarn.lock
Labels: NEED 1 REVIEW

#152 E2e test change
  cypress/e2e/editor.spec.cy.ts
Labels: NEED 1 REVIEW

#154 Fix the login redirect issue in production
  .github/workflows/ci-cd.yml
  cypress/e2e/editor.spec.cy.ts
  docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/development/environment.md
  hashicorp/images/nginx-ssl-app.conf
  hashicorp/instances/app.tf
  hashicorp/scripts/setup-app.sh
  package.json
Labels: BUG, CI/CD, WIP

#160 Running unit and e2e tests in parallel
  .github/workflows/ci-cd.yml
Labels: CI/CD

#162 Add redirect in prod environment
  .github/workflows/ci-cd.yml
  packages/nexusgraph-app/src/App.tsx
Labels: BUG

#166 Fix master sonar cloud error
  packages/nexusgraph-graph/src/VisualizationView.tsx
Labels: MERGEABLE

#149 Add check-list button
  cypress/e2e/editor.spec.cy.ts
  packages/nexusgraph-editor/src/Lexical/LexicalEditor.tsx
  packages/nexusgraph-editor/src/Lexical/plugins/ToolbarPlugin.tsx
  packages/nexusgraph-editor/src/Lexical/plugins/styled.ts
  packages/nexusgraph-editor/src/Lexical/themes/ExampleTheme.js
Labels: MERGEABLE

#155 Add font-size and font-family button
  cypress/e2e/font-family-dropdown.spec.cy.ts
  cypress/e2e/font-size-dropdown.spec.cy.ts
  packages/nexusgraph-editor/src/Lexical/plugins/DropDown.tsx
  packages/nexusgraph-editor/src/Lexical/plugins/ToolbarPlugin.test.tsx
  packages/nexusgraph-editor/src/Lexical/plugins/ToolbarPlugin.tsx
  packages/nexusgraph-editor/src/Lexical/plugins/styled.ts
Labels: MERGEABLE

#168 Add indent and outdent button
  cypress/e2e/align-dropdown.spec.cy.ts
  cypress/e2e/editor.spec.cy.ts
  packages/nexusgraph-editor/src/Lexical/plugins/RichTextDropDown.tsx
  packages/nexusgraph-editor/src/Lexical/plugins/ToolbarPlugin.test.tsx
  packages/nexusgraph-editor/src/Lexical/plugins/ToolbarPlugin.tsx
  packages/nexusgraph-editor/src/Lexical/plugins/styled.ts
Labels: MERGEABLE

#173 Implement a pluggable architecture for nlp package
  babel.config.json
  docs/docs/development/img/nexusgraph-architecture.drawio
  docs/docs/development/img/nexusgraph-architecture.png
  docs/docs/development/img/nexusgraph-separation-of-concerns.drawio
  docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/development/architecture.md
  docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/development/img/nexusgraph-separation-of-concerns.drawio
  package.json
  packages/nexusgraph-app/src/App.tsx
  packages/nexusgraph-nlp/index.ts
  packages/nexusgraph-nlp/inversify.config.ts
  packages/nexusgraph-nlp/package.json
  packages/nexusgraph-nlp/src/BasicSVOParser.ts
  packages/nexusgraph-nlp/src/processor/RemoteNaturalLanguageProcessor.test.ts
  packages/nexusgraph-nlp/src/processor/RemoteNaturalLanguageProcessor.ts
  packages/nexusgraph-server/.yarn/install-state.gz
  packages/nexusgraph-server/src/server.ts
  tsconfig.json
  yarn.lock
Labels: MERGEABLE

#169 Add font-color button
  cypress/e2e/font-color.spec.cy.ts
  packages/nexusgraph-editor/src/Lexical/plugins/ColorPicker.tsx
  packages/nexusgraph-editor/src/Lexical/plugins/DropDown.tsx
  packages/nexusgraph-editor/src/Lexical/plugins/DropdownColorPicker.tsx
  packages/nexusgraph-editor/src/Lexical/plugins/TextInput.tsx
  packages/nexusgraph-editor/src/Lexical/plugins/ToolbarPlugin.tsx
  packages/nexusgraph-editor/src/Lexical/plugins/styled.ts
Labels: MERGEABLE

#175 Speed Up E2E Tests
  .github/scripts/dev-e2e-test-script.sh
  .github/scripts/prod-e2e-test-script.sh
  .github/workflows/ci-cd.yml
  .github/workflows/e2e-tests.yml
  cypress/e2e/node-inspector-panel.spec.cy.ts
Labels: CI/CD, MERGEABLE

#172 Add clear formatting button
  cypress/e2e/clear-formatting.spec.cy.ts
  packages/nexusgraph-editor/src/Lexical/plugins/ToolbarPlugin.tsx
  packages/nexusgraph-editor/src/Lexical/plugins/styled.ts
Labels: MERGEABLE

#150 Support graph export
  .github/dbInDev.json
  .github/dbInProd.json
  .github/scripts/dev-e2e-test-script.sh
  .github/scripts/prod-e2e-test-script.sh
  .github/workflows/ci-cd.yml
  .github/workflows/e2e-tests.yml
  .gitignore
  custom.d.ts
  cypress.config.ts
  cypress/downloads/graph.png
  cypress/downloads/graph.svg
  cypress/e2e/0.login.spec.cy.ts
  cypress/e2e/align-dropdown.spec.cy.ts
  cypress/e2e/clear-formatting.spec.cy.ts
  cypress/e2e/editor.spec.cy.ts
  cypress/e2e/font-color.spec.cy.ts
  cypress/e2e/font-family-dropdown.spec.cy.ts
  cypress/e2e/font-size-dropdown.spec.cy.ts
  cypress/e2e/graph-export-button.spec.cy.ts
  cypress/e2e/nexusgraph.spec.cy.ts
  cypress/e2e/node-inspector-panel.spec.cy.ts
  cypress/tsconfig.json
  docs/docs/development/nexusgraph-server.md
  jest.config.json
  packages/nexusgraph-graph/package.json
  packages/nexusgraph-graph/public/save.svg
  packages/nexusgraph-graph/src/GraphBrowser.tsx
  packages/nexusgraph-graph/src/export-button/ExportButton.tsx
  packages/nexusgraph-graph/src/export-button/imageUtils.ts
  packages/nexusgraph-graph/src/export-button/svgUtils.ts
  packages/nexusgraph-graph/src/inspection-panel/NodeInspectorPanel.tsx
  packages/nexusgraph-graph/src/styles/ExportButtn.styled.ts
  packages/nexusgraph-graph/src/styles/InspectorContainer.styled.ts
  packages/nexusgraph-server/package.json
  packages/nexusgraph-server/src/server.test.ts
  packages/nexusgraph-server/src/server.ts
  packages/nexusgraph-server/tsconfig.json
  packages/nexusgraph-server/yarn.lock
  tsconfig.json
  yarn.lock
Labels: CI/CD, MERGEABLE

#179 Use reusable E2E workflows
  .env.test
  .github/db.json
  .github/dbInProd.json
  .github/scripts/prod-e2e-test-script.sh
  .github/test-setup.sh
  .github/workflows/ci-cd.yml
  .github/workflows/e2e-tests.yml
  packages/nexusgraph-server/src/server.ts
Labels: CI/CD, MERGEABLE

#178 Nexusgraph supports i8n
  .github/workflows/ci-cd.yml
  cypress/e2e/i18n.spec.cy.ts
  docs/docs/development/ci-cd.md
  i18n.js
  package.json
  packages/nexusgraph-app/src/index.tsx
  packages/nexusgraph-graph/src/GraphVisualizer.tsx
  packages/nexusgraph-graph/src/data/graph.json
  packages/nexusgraph-graph/src/data/graphI18n.test.tsx
  packages/nexusgraph-graph/src/inspection-panel/NodeInspectorPanel.tsx
  packages/nexusgraph-graph/src/inspection-panel/PropertiesTable.tsx
  packages/nexusgraph-graph/src/inspection-panel/properties-panel-content/ClickableUrls.tsx
  packages/nexusgraph-graph/src/inspection-panel/properties-panel-content/DetailsPane.tsx
  packages/nexusgraph-graph/src/inspection-panel/properties-panel-content/OverviewPane.tsx
  packages/nexusgraph-graph/src/inspection-panel/properties-panel-content/StyleableNodeLabel.tsx
  packages/nexusgraph-graph/src/inspection-panel/properties-panel-content/StyleableRelType.tsx
  tsconfig.json
  yarn.lock
Labels: NEED 1 REVIEW

#181 Enhance Lexical plugin source structure
  packages/nexusgraph-editor/src/Lexical/LexicalEditor.tsx
  packages/nexusgraph-editor/src/Lexical/plugins/CodeHighlightPlugin/index.ts
  packages/nexusgraph-editor/src/Lexical/plugins/ToolbarPlugin/ToolbarPlugin.test.tsx
  packages/nexusgraph-editor/src/Lexical/plugins/ToolbarPlugin/index.tsx
  packages/nexusgraph-editor/src/Lexical/plugins/ToolbarPlugin/styled.ts
  packages/nexusgraph-editor/src/Lexical/ui/ColorPicker.tsx
  packages/nexusgraph-editor/src/Lexical/ui/DropDown.tsx
  packages/nexusgraph-editor/src/Lexical/ui/DropdownColorPicker.tsx
  packages/nexusgraph-editor/src/Lexical/ui/TextInput.tsx
Labels: MERGEABLE, EDITOR, REFACTOR

#189 Update package relationship diagram
  docs/docs/development/img/nexusgraph-separation-of-concerns.drawio
  docs/docs/development/img/nexusgraph-separation-of-concerns.png
Labels: DOCUMENTATION, MERGEABLE
