Repository paion-data/nexusgraph, pull requests merged in 2023-06, with the labels that each got.

#65 Update links & release namespace in fork
  docs/README.md
  docs/docs/development/getting-started.md
  docs/docusaurus.config.js
  package.json
  packages/messier-61-graph/package.json
  packages/messier-61-graphql-server/package.json
Labels: BUG, CI/CD, DOCUMENTATION, MERGEABLE

#67 Consolidate CI/CD definitions
  .github/workflows/ci-cd.yml
Labels: CI/CD, MERGEABLE

#68 Remove deprecated actions
  .github/workflows/release.yml
  .github/workflows/test.yml
  README.md
Labels: CI/CD, MERGEABLE

#69 Update copyright header
  .eslintignore
  .github/tag-for-release.bash
  .github/upversion.py
  .github/workflows/ci-cd.yml
  .gitignore
  .yamllint
  config/jest/cssTransform.js
  config/jest/fileTransform.js
  config/webpack/webpack.config.js
  config/webpack/webpackDevServer.config.js
  docs/.gitignore
  docs/babel.config.js
  docs/docusaurus.config.js
  docs/scripts/typedoc.js
  docs/sidebars.js
  docs/src/components/HomepageFeatures/index.tsx
  docs/src/components/HomepageFeatures/styles.module.css
  docs/src/css/custom.css
  docs/src/pages/index.module.css
  docs/src/pages/index.tsx
  packages/messier-61-app/App.test.tsx
  packages/messier-61-app/App.tsx
  packages/messier-61-app/index.css
  packages/messier-61-app/index.tsx
  packages/messier-61-app/messier-61-env.d.ts
  packages/messier-61-app/setupTests.ts
  packages/messier-61-editor/Editor.test.tsx
  packages/messier-61-editor/Editor.tsx
  packages/messier-61-editor/Lexical/LexicalEditor.module.css
  packages/messier-61-editor/Lexical/LexicalEditor.test.tsx
  packages/messier-61-editor/Lexical/LexicalEditor.tsx
  packages/messier-61-editor/Lexical/LexicalEditorConfig.ts
  packages/messier-61-editor/Lexical/index.ts
  packages/messier-61-editor/Lexical/parser/RawTextParser.test.ts
  packages/messier-61-editor/Lexical/parser/RawTextParser.ts
  packages/messier-61-editor/Lexical/parser/index.ts
  packages/messier-61-editor/Lexical/plugins/Messier61OnChangePlugin.tsx
  packages/messier-61-editor/index.ts
  packages/messier-61-external-brain/Transformer.tsx
  packages/messier-61-external-brain/index.ts
  packages/messier-61-graph/src/ForceSimulation.ts
  packages/messier-61-graph/src/models/Graph.ts
  packages/messier-61-graph/src/models/Node.ts
  packages/messier-61-graph/src/models/Relationship.ts
  packages/messier-61-graph/src/models/VizItemProperty.ts
  packages/messier-61-graph/temporary/D3Graph/index.ts
  packages/messier-61-graph/temporary/Graph.tsx
  packages/messier-61-graph/temporary/GraphConfig.d.ts
  packages/messier-61-graph/temporary/GraphDataMaker.test.ts
  packages/messier-61-graph/temporary/GraphDataMaker.ts
  packages/messier-61-graph/temporary/index.ts
  packages/messier-61-graphql-server/package.json
  packages/messier-61-home/Home.module.css
  packages/messier-61-home/Home.test.tsx
  packages/messier-61-home/index.ts
  packages/messier-61-nlp/BasicSVOParser.ts
  scripts/build.js
  scripts/start.js
Labels: DOCUMENTATION, MERGEABLE

#70 Update CI/CD
  .github/workflows/ci-cd.yml
Labels: CI/CD, MERGEABLE

#72 Automatically publish Messier-61 AMI image and deploy it to EC2 through HashiCorp
  .github/workflows/ci-cd.yml
  docs/README.md
  docs/docs/development/getting-started.md
  docs/docusaurus.config.js
  hashicorp/images/aws-mlflow-base.pkr.hcl
  hashicorp/images/variables.pkr.hcl
  hashicorp/instances/main.tf
  hashicorp/scripts/setup.sh
Labels: CI/CD, MERGEABLE

#74 Enable i18n on landing page
  README.md
  packages/messier-61-app/package.json
  packages/messier-61-app/src/App.jsx
  packages/messier-61-app/src/components/Team.jsx
  packages/messier-61-app/src/components/about.jsx
  packages/messier-61-app/src/components/footer.jsx
  packages/messier-61-app/src/components/header.jsx
  packages/messier-61-app/src/components/navigation.jsx
  packages/messier-61-app/src/components/services.jsx
  packages/messier-61-app/src/data/data.json
  packages/messier-61-app/src/i18n.js
  packages/messier-61-app/src/index.js
  packages/messier-61-app/yarn.lock
Labels: MERGEABLE

#75 Auto update contributor on every master commit
  .github/workflows/contributors.yml
  README.md
Labels: CI/CD, MERGEABLE

#76 Add investor image
  .github/workflows/contributors.yml
  README.md
  packages/messier-61-app/public/img/team/02.jpg
  packages/messier-61-app/public/img/team/investor.png
  packages/messier-61-app/src/components/Team.jsx
Labels: MERGEABLE

#77 Use 'HashiCorp AWS' action for deployment
  .github/workflows/ci-cd.yml
Labels: CI/CD, MERGEABLE

#78 Update landing page README
  packages/messier-61-app/README.md
Labels: DOCUMENTATION, MERGEABLE

#79 Add Landing Page Test
  .github/workflows/ci-cd.yml
  babel.config.json
  packages/messier-61-app/package.json
  packages/messier-61-app/src/components/Team.jsx
  packages/messier-61-app/src/components/Team.test.jsx
  packages/messier-61-app/src/components/__snapshots__/Team.test.jsx.snap
  packages/messier-61-app/src/components/__snapshots__/about.test.jsx.snap
  packages/messier-61-app/src/components/__snapshots__/footer.test.jsx.snap
  packages/messier-61-app/src/components/__snapshots__/header.test.jsx.snap
  packages/messier-61-app/src/components/__snapshots__/image.test.jsx.snap
  packages/messier-61-app/src/components/__snapshots__/navigation.test.jsx.snap
  packages/messier-61-app/src/components/__snapshots__/services.test.jsx.snap
  packages/messier-61-app/src/components/about.jsx
  packages/messier-61-app/src/components/about.test.jsx
  packages/messier-61-app/src/components/footer.jsx
  packages/messier-61-app/src/components/footer.test.jsx
  packages/messier-61-app/src/components/header.jsx
  packages/messier-61-app/src/components/header.test.jsx
  packages/messier-61-app/src/components/image.test.jsx
  packages/messier-61-app/src/components/navigation.jsx
  packages/messier-61-app/src/components/navigation.test.jsx
  packages/messier-61-app/src/components/services.jsx
  packages/messier-61-app/src/components/services.test.jsx
  packages/messier-61-app/yarn.lock
Labels: MERGEABLE

#32 Implement arrow, test and document
  docs/static/img/typedoc/straight-arrow-document.ai
  docs/static/img/typedoc/straight-arrow-document.png
  packages/messier-61-graph/src/ArcArrow.ts
  packages/messier-61-graph/src/LoopArrow.test.ts
  packages/messier-61-graph/src/LoopArrow.ts
  packages/messier-61-graph/src/Point.ts
  packages/messier-61-graph/src/StraightArrow.test.ts
  packages/messier-61-graph/src/StraightArrow.ts
Labels: DOCUMENTATION, MERGEABLE, GRAPH

#34 Implement Graph React Component
  packages/messier-61-graph/package.json
  packages/messier-61-graph/src/ForceSimulation.ts
  packages/messier-61-graph/src/Graph.tsx
  packages/messier-61-graph/src/GraphGeometryModel.ts
  packages/messier-61-graph/src/GraphStats.test.ts
  packages/messier-61-graph/src/GraphStats.ts
  packages/messier-61-graph/src/GraphStyle.ts
  packages/messier-61-graph/src/GraphVisualizer.tsx
  packages/messier-61-graph/src/PairwiseArcsRelationshipRouting.ts
  packages/messier-61-graph/src/Renderer.ts
  packages/messier-61-graph/src/Visualization.ts
  packages/messier-61-graph/src/VizItem.ts
  packages/messier-61-graph/src/WheelZoomInfoOverlay.tsx
  packages/messier-61-graph/src/event-handler/GraphEventHandlerModel.test.ts
  packages/messier-61-graph/src/event-handler/GraphEventHandlerModel.ts
  packages/messier-61-graph/src/event-handler/NodeEventHandler.ts
  packages/messier-61-graph/src/event-handler/RelationshipEventHandlers.ts
  packages/messier-61-graph/src/inspection-panel/ClickableUrls.tsx
  packages/messier-61-graph/src/inspection-panel/ClipboardCopier.tsx
  packages/messier-61-graph/src/inspection-panel/DefaultDetailsPane.tsx
  packages/messier-61-graph/src/inspection-panel/DefaultOverviewPane.tsx
  packages/messier-61-graph/src/inspection-panel/NodeInspectorDrawer.tsx
  packages/messier-61-graph/src/inspection-panel/NodeInspectorPanel.tsx
  packages/messier-61-graph/src/inspection-panel/NodeLabel.tsx
  packages/messier-61-graph/src/inspection-panel/PropertiesTable.tsx
  packages/messier-61-graph/src/inspection-panel/RelType.tsx
  packages/messier-61-graph/src/inspection-panel/ShowMoreOrAll.tsx
  packages/messier-61-graph/src/inspection-panel/WarningMessage.tsx
  packages/messier-61-graph/src/models/Graph.ts
  packages/messier-61-graph/src/models/Relationship.ts
  packages/messier-61-graph/src/styles/DefaultPane.styled.ts
  packages/messier-61-graph/src/styles/InspectorContainer.styled.ts
  packages/messier-61-graph/src/styles/LabelAndReltypesChip.styled.ts
  packages/messier-61-graph/src/styles/PropertiesTable.styled.ts
  packages/messier-61-graph/src/styles/StyledShowMoreButton.styled.ts
  packages/messier-61-graph/src/styles/WheelZoomInfoOverlay.styled.ts
  packages/messier-61-graph/src/styles/themes.tsx
  packages/messier-61-graph/src/textMeasurement.ts
  packages/messier-61-graph/tsconfig.json
  packages/messier-61-graph/yarn.lock
  tsconfig.json
Labels: MERGEABLE, GRAPH

#82 Creat App Module
  config/webpack/webpack.config.js
  package.json
  packages/messier-61-app/package.json
  packages/messier-61-app/public/favicon.ico
  packages/messier-61-app/public/index.html
  packages/messier-61-app/public/logo192.png
  packages/messier-61-app/public/logo512.png
  packages/messier-61-app/public/manifest.json
  packages/messier-61-app/public/robots.txt
  packages/messier-61-app/src/App.tsx
  packages/messier-61-app/src/index.css
  packages/messier-61-app/src/index.tsx
  packages/messier-61-app/yarn.lock
  yarn.lock
Labels: MERGEABLE, NEW FEATURE

#83 编写 Messier-61 推广文档
  docs/docs/concepts/_category_.json
  docs/docs/concepts/img/summary.png
  docs/docs/concepts/index.md
  docs/docs/graph/_category_.json
  docs/docs/graph/d3.mdx
  docs/docs/graph/img/enter-example-1.png
  docs/docs/graph/img/enter-example-2.png
  docs/docs/graph/img/enter-example-3.png
  docs/docs/graph/img/phyllotaxis-arrangement.png
  docs/docs/intro.md
  docs/docusaurus.config.js
  docs/src/components/HomepageFeatures/index.tsx
  docs/src/pages/index.tsx
  docs/static/img/cloud-native.svg
  docs/static/img/github.svg
  docs/static/img/machine-learning.svg
  docs/static/img/undraw_docusaurus_mountain.svg
  docs/static/img/undraw_docusaurus_react.svg
  docs/static/img/undraw_docusaurus_tree.svg
Labels: DOCUMENTATION, MERGEABLE

#84 Implementation Visualization View Module
  package.json
  packages/messier-61-graph/src/GraphVisualizer.tsx
  packages/messier-61-graph/src/models/Relationship.ts
  packages/messier-61-graph/src/visualization-view/VisualizationView.styled.tsx
  packages/messier-61-graph/src/visualization-view/VisualizationView.tsx
  packages/messier-61-graph/yarn.lock
  yarn.lock
Labels: MERGEABLE, GRAPH, NEW FEATURE

#85 Realize the linkage between Editor and VisualizationView
  package.json
  packages/messier-61-app/src/App.tsx
  packages/messier-61-app/src/index.tsx
  packages/messier-61-graph/src/GraphVisualizer.tsx
  packages/messier-61-graph/src/graph-browser/GraphBrowser.tsx
  packages/messier-61-graph/src/shared/editor/editorDuck.ts
  packages/messier-61-graph/src/shared/globalState.ts
  packages/messier-61-graph/src/shared/rootReducer.ts
  packages/messier-61-graph/src/visualization-view/VisualizationView.tsx
  packages/messier-61-graph/src/visualization-view/custom.d.ts
  yarn.lock
Labels: MERGEABLE, NEW FEATURE

#86 添加 SonarCloud 代码分析徽章
  README.md
Labels: CI/CD, MERGEABLE
