Repository paion-data/nexusgraph, pull requests merged in 2023-10, with the labels that each got.

#223 Update HashiCorp deployment configs
  .github/workflows/ci-cd.yml
  docs/docs/development/9-ci-cd.md
  hashicorp/images/aws-app-nexusgraph-com.pkr.hcl
  hashicorp/images/nginx-ssl-app.conf
  hashicorp/images/variables.pkr.hcl
  hashicorp/instances/app-nexusgraph-com.tf
  hashicorp/instances/variables.auto.tfvars
  hashicorp/scripts/aws-app-nexusgraph-com-pkr-setup.sh
Labels: CI/CD, MERGEABLE, REFACTORING

#222 Implement sidebar intelligent ai
  custom.d.ts
  package.json
  packages/nexusgraph-app/src/App.tsx
  packages/nexusgraph-app/src/ReduxHook.tsx
  packages/nexusgraph-app/src/note-title-input/styled.ts
  packages/nexusgraph-app/src/sidebar/CreateButton.tsx
  packages/nexusgraph-app/src/sidebar/FeatureMenu.tsx
  packages/nexusgraph-app/src/sidebar/Modal.tsx
  packages/nexusgraph-app/src/sidebar/img/nlp.png
  packages/nexusgraph-app/src/sidebar/styled.ts
  packages/nexusgraph-app/src/sidebar/useModal.tsx
  packages/nexusgraph-app/src/styled.ts
  packages/nexusgraph-nlp/src/processor/NaturalLanguageProcessor.ts
  packages/nexusgraph-nlp/src/processor/RemoteNaturalLanguageProcessor.test.ts
  packages/nexusgraph-nlp/src/processor/RemoteNaturalLanguageProcessor.ts
  packages/nexusgraph-redux/index.ts
  packages/nexusgraph-redux/src/globalState.ts
  packages/nexusgraph-redux/src/intelligentAI/intelligentAIDuck.ts
  packages/nexusgraph-redux/src/rootReducer.ts
  yarn.lock
Labels: MERGEABLE, NEED REBASE

#224 Fix deployment error
  .github/workflows/ci-cd.yml
  hashicorp/images/aws-app-nexusgraph-com.pkr.hcl
  hashicorp/instances/app-nexusgraph-com.tf
Labels: BUG, CI/CD, REFACTORING, NEED 1 REVIEW

#227 Implement textarea content parser
  packages/nexusgraph-graph/src/VisualizationView.tsx
  packages/nexusgraph-graph/src/processor/NodesExpand.ts
  packages/nexusgraph-nlp/src/parser/EditorContentParser.test.ts
  packages/nexusgraph-nlp/src/parser/EditorContentParser.ts
  packages/nexusgraph-nlp/src/parser/TextareaContentParser.test.ts
  packages/nexusgraph-nlp/src/parser/TextareaContentParser.ts
  packages/nexusgraph-nlp/src/parser/index.ts
  packages/nexusgraph-nlp/src/parser/json/LexicalEditorStateParser-basic.json
  packages/nexusgraph-nlp/src/parser/json/LexicalEditorStateParser-parseLine-basic.json
  packages/nexusgraph-nlp/src/parser/json/LexicalEditorStateParser-with-empty-line.json
  packages/nexusgraph-nlp/src/parser/json/raw-text-parser-happy-path.json
  packages/nexusgraph-nlp/src/processor/RemoteNaturalLanguageProcessor.test.ts
  packages/nexusgraph-nlp/src/processor/RemoteNaturalLanguageProcessor.ts
Labels: NLP, MERGEABLE, REFACTORING

#228 Wait for the test to pass and then publish
  .github/workflows/ci-cd.yml
Labels: CI/CD

#229 Perfect i18n
  cypress/e2e/i18n.spec.cy.ts
  cypress/support/commands.ts
  cypress/support/global.d.ts
  packages/nexusgraph-app/src/sidebar/FeatureMenu.tsx
  packages/nexusgraph-i18n/index.ts
  packages/nexusgraph-i18n/src/graph/graph.json
  packages/nexusgraph-redux/src/note/noteDuck.ts
Labels: MERGEABLE

#233 Add button hover style
  packages/nexusgraph-app/src/sidebar/FeatureMenu.tsx
  packages/nexusgraph-app/src/sidebar/styled.ts
Labels: MERGEABLE, REFACTORING

#234 Implement alert when no graph data is returned from NLP
  package.json
  packages/nexusgraph-app/src/sidebar/Alert.tsx
  packages/nexusgraph-app/src/sidebar/styled.ts
  packages/nexusgraph-i18n/src/graph/graph.json
  yarn.lock
Labels: MERGEABLE

#235 Warning when nlp data is null
  cypress.config.ts
  cypress/e2e/alert.spec.cy.ts
  cypress/fixtures/getEditorData.json
  cypress/fixtures/getNlpRespond.json
  packages/nexusgraph-app/src/App.tsx
  packages/nexusgraph-app/src/ReduxHook.tsx
  packages/nexusgraph-app/src/component/Alert.tsx
  packages/nexusgraph-app/src/sidebar/CreateButton.tsx
  packages/nexusgraph-app/src/sidebar/FeatureMenu.tsx
  packages/nexusgraph-app/src/sidebar/styled.ts
  packages/nexusgraph-redux/index.ts
  packages/nexusgraph-redux/src/globalState.ts
  packages/nexusgraph-redux/src/intelligentAI/intelligentAIDuck.ts
  packages/nexusgraph-redux/src/rootReducer.ts
Labels: NLP, MERGEABLE, NEW FEATURE, REFACTORING

#236 Change for relationship style
  packages/nexusgraph-graph/src/GraphStyle.ts
  packages/nexusgraph-graph/src/styles/WheelZoomInfoOverlay.styled.ts
Labels: MERGEABLE

#240 Connect to theresa Middleware
  .env.test
  packages/nexusgraph-nlp/src/processor/RemoteNaturalLanguageProcessor.test.ts
  packages/nexusgraph-nlp/src/processor/RemoteNaturalLanguageProcessor.ts
Labels: MERGEABLE

#242 Update docs
  docs/docs/development/9-ci-cd.md
  packages/nexusgraph-app/src/App.tsx
  packages/nexusgraph-app/src/styled.ts
Labels: MERGEABLE, DOCUMENTATION

#243 New App layout
  .prettierignore
  packages/nexusgraph-app/public/user.svg
  packages/nexusgraph-app/src/App.tsx
  packages/nexusgraph-app/src/component/Alert.tsx
  packages/nexusgraph-app/src/component/NoteTitleInput.tsx
  packages/nexusgraph-app/src/component/sidebar/CreateButton.tsx
  packages/nexusgraph-app/src/component/sidebar/FeatureMenu.tsx
  packages/nexusgraph-app/src/component/sidebar/Modal.tsx
  packages/nexusgraph-app/src/component/sidebar/img/nlp.png
  packages/nexusgraph-app/src/component/sidebar/styled.ts
  packages/nexusgraph-app/src/component/sidebar/useModal.tsx
  packages/nexusgraph-app/src/note-title-input/styled.ts
  packages/nexusgraph-app/src/styled.ts
  packages/nexusgraph-graph/src/GraphBrowser.tsx
  packages/nexusgraph-graph/src/export-button/ExportButton.tsx
Labels: MERGEABLE, REFACTORING

#245 Bind access token and user id to app context
  packages/nexusgraph-app/inversify.config.ts
  packages/nexusgraph-app/src/DevApp.tsx
  packages/nexusgraph-app/src/ProdApp.tsx
Labels: MERGEABLE, REFACTORING
