Repository paion-data/nexusgraph, pull requests merged in 2023-07, with the labels that each got.

#87 整理并简化 GraphModel 的封装调用逻辑
  package.json
  packages/messier-61-app/src/App.tsx
  packages/messier-61-app/src/index.tsx
  packages/messier-61-graph/index.ts
  packages/messier-61-graph/src/ErrorBoundary.tsx
  packages/messier-61-graph/src/Graph.tsx
  packages/messier-61-graph/src/GraphBrowser.tsx
  packages/messier-61-graph/src/GraphVisualizer.tsx
  packages/messier-61-graph/src/VisualizationView.styled.tsx
  packages/messier-61-graph/src/VisualizationView.tsx
  packages/messier-61-graph/src/custom.d.ts
  packages/messier-61-graph/src/graph-browser/GraphBrowser.tsx
  packages/messier-61-graph/src/shared/editor/editorDuck.ts
  packages/messier-61-graph/src/shared/globalState.ts
  packages/messier-61-graph/src/visualization-view/VisualizationView.tsx
  packages/messier-61-graph/temporary/D3Graph/D3Graph.module.css
  packages/messier-61-graph/temporary/D3Graph/D3Graph.test.tsx
  packages/messier-61-graph/temporary/D3Graph/D3Graph.tsx
  packages/messier-61-graph/temporary/D3Graph/index.ts
  packages/messier-61-graph/temporary/Graph.tsx
  packages/messier-61-graph/temporary/GraphConfig.d.ts
  packages/messier-61-graph/temporary/GraphDataMaker.test.ts
  packages/messier-61-graph/temporary/GraphDataMaker.ts
  packages/messier-61-graph/temporary/GraphDecorator.test.ts
  packages/messier-61-graph/temporary/GraphDecorator.ts
  packages/messier-61-graph/temporary/index.ts
Labels: MERGEABLE

#88 Setting Graph Style
  package.json
  packages/messier-61-app/src/App.tsx
  packages/messier-61-app/src/index.tsx
  packages/messier-61-graph/index.ts
  packages/messier-61-graph/src/Graph.tsx
  packages/messier-61-graph/src/GraphBrowser.tsx
  packages/messier-61-graph/src/GraphVisualizer.tsx
  packages/messier-61-graph/src/VisualizationView.styled.tsx
  packages/messier-61-graph/src/VisualizationView.tsx
  packages/messier-61-graph/src/custom.d.ts
  packages/messier-61-graph/src/graph-browser/GraphBrowser.tsx
  packages/messier-61-graph/src/shared/editor/editorDuck.ts
  packages/messier-61-graph/src/shared/globalState.ts
  packages/messier-61-graph/src/visualization-view/VisualizationView.tsx
  packages/messier-61-graph/temporary/D3Graph/D3Graph.module.css
  packages/messier-61-graph/temporary/D3Graph/D3Graph.test.tsx
  packages/messier-61-graph/temporary/D3Graph/D3Graph.tsx
  packages/messier-61-graph/temporary/D3Graph/index.ts
  packages/messier-61-graph/temporary/Graph.tsx
  packages/messier-61-graph/temporary/GraphConfig.d.ts
  packages/messier-61-graph/temporary/GraphDataMaker.test.ts
  packages/messier-61-graph/temporary/GraphDataMaker.ts
  packages/messier-61-graph/temporary/GraphDecorator.test.ts
  packages/messier-61-graph/temporary/GraphDecorator.ts
  packages/messier-61-graph/temporary/index.ts
  packages/messier-61-graph/yarn.lock
  yarn.lock
Labels: MERGEABLE

#90 Setting App Style
  package.json
  packages/messier-61-app/src/App.tsx
  packages/messier-61-app/src/styled.ts
  packages/messier-61-graph/package.json
  packages/messier-61-graph/src/GraphBrowser.tsx
  yarn.lock
Labels: MERGEABLE

#89 Switching to yarn 2
  .github/workflows/ci-cd.yml
  .gitignore
  .yarn/releases/yarn-3.6.1.cjs
  .yarnrc.yml
  package.json
  packages/messier-61-app/yarn.lock
  packages/messier-61-editor/index.ts
  packages/messier-61-editor/package.json
  packages/messier-61-editor/src/Editor.test.tsx
  packages/messier-61-editor/src/Editor.tsx
  packages/messier-61-editor/src/Lexical/LexicalEditor.module.css
  packages/messier-61-editor/src/Lexical/LexicalEditor.test.tsx
  packages/messier-61-editor/src/Lexical/LexicalEditor.tsx
  packages/messier-61-editor/src/Lexical/LexicalEditorConfig.ts
  packages/messier-61-editor/src/Lexical/index.ts
  packages/messier-61-editor/src/Lexical/parser/RawTextParser.test.ts
  packages/messier-61-editor/src/Lexical/parser/RawTextParser.ts
  packages/messier-61-editor/src/Lexical/parser/index.ts
  packages/messier-61-editor/src/Lexical/parser/json/raw-text-parser-happy-path.json
  packages/messier-61-editor/src/Lexical/plugins/Messier61OnChangePlugin.tsx
  packages/messier-61-external-brain/ExternalBrain.module.css
  packages/messier-61-external-brain/ExternalBrain.tsx
  packages/messier-61-external-brain/Transformer.tsx
  packages/messier-61-external-brain/index.ts
  packages/messier-61-graph/package.json
  packages/messier-61-graph/yarn.lock
  packages/messier-61-landing-page/package.json
  packages/messier-61-landing-page/yarn.lock
  yarn.lock
Labels: BREAKING CHANGE, MERGEABLE

#93 Support Node Pane Expansion
  packages/messier-61-graph/src/GraphStyle.ts
  packages/messier-61-graph/src/GraphVisualizer.tsx
  packages/messier-61-graph/src/inspection-panel/NodeLabel.tsx
  packages/messier-61-graph/src/inspection-panel/properties-panel-content/properties-panel-content/DetailsPane.tsx
  packages/messier-61-graph/src/shared/editor/editorDuck.ts
Labels: MERGEABLE

#94 Graph Event Handler Debug
  packages/messier-61-graph/src/event-handler/NodeEventHandler.ts
  packages/messier-61-graph/src/event-handler/RelationshipEventHandlers.ts
Labels: MERGEABLE

#95 Update documentations
  .github/workflows/ci-cd.yml
  .gitignore
  docs/docs/development/ci-cd.md
  docs/docs/development/getting-started.md
  docs/package.json
  docs/yarn.lock
  package.json
  packages/messier-61-graph/src/shared/globalState.ts
  packages/messier-61-landing-page/README.md
  packages/messier-61-landing-page/yarn.lock
Labels: DOCUMENTATION, MERGEABLE

#96 Page Style Definition
  packages/messier-61-app/src/App.tsx
  packages/messier-61-app/src/styled.ts
  packages/messier-61-editor/src/Lexical/LexicalEditor.module.css
  packages/messier-61-graph/src/Graph.tsx
  packages/messier-61-graph/src/WheelZoomInfoOverlay.tsx
  packages/messier-61-graph/src/styles/DefaultPane.styled.ts
  packages/messier-61-graph/src/styles/InspectorContainer.styled.ts
Labels: MERGEABLE

#98 Automatically deploy landing page
  .github/workflows/ci-cd.yml
  hashicorp/images/aws-messier-61-base.pkr.hcl
  hashicorp/images/aws-nexusgraph-landing-page.pkr.hcl
  hashicorp/images/nginx-ssl-landing-page.conf
  hashicorp/instances/main-landing-page.auto.tfvars
  hashicorp/instances/main-landing-page.tf
  hashicorp/instances/main.tf
  hashicorp/scripts/setup-landing-page.sh
  hashicorp/scripts/setup.sh
Labels: CI/CD, MERGEABLE

#101 Fix app.nexusgraph.com server config issue
  hashicorp/images/nginx-ssl-app.conf
  hashicorp/instances/app.tf
Labels: BUG, CI/CD, MERGEABLE

#102 Fix domain typo
  hashicorp/instances/app.tf
Labels: MERGEABLE

#97 Implement remote nlp processor
  .github/workflows/ci-cd.yml
  docs/yarn.lock
  packages/nexusgraph-editor/package.json
  packages/nexusgraph-editor/src/Lexical/plugins/NexusgraphOnChangePlugin.tsx
  packages/nexusgraph-editor/src/Lexical/processor/NaturalLanguageProcessor.ts
  packages/nexusgraph-editor/src/Lexical/processor/RemoteNaturalLanguageProcessor.test.ts
  packages/nexusgraph-editor/src/Lexical/processor/RemoteNaturalLanguageProcessor.ts
  packages/nexusgraph-graph/index.ts
  packages/nexusgraph-graphql-server/src/server.ts
  yarn.lock
Labels: MERGEABLE, NEED CHANGES

#104 Enable sentry.io monitoring for app.nexusgraph.com
  .github/workflows/ci-cd.yml
  packages/nexusgraph-app/package.json
  packages/nexusgraph-app/src/index.tsx
  yarn.lock
Labels: MERGEABLE

#105 Implement Item Details Panel
  packages/nexusgraph-graph/package.json
  packages/nexusgraph-graph/src/GraphVisualizer.tsx
  packages/nexusgraph-graph/src/Visualization.ts
  packages/nexusgraph-graph/src/event-handler/GraphEventHandlerModel.ts
  packages/nexusgraph-graph/src/event-handler/NodeEventHandler.ts
  packages/nexusgraph-graph/src/event-handler/RelationshipEventHandlers.ts
  packages/nexusgraph-graph/src/inspection-panel/DefaultDetailsPane.tsx
  packages/nexusgraph-graph/src/inspection-panel/NodeInspectorPanel.tsx
  packages/nexusgraph-graph/src/inspection-panel/properties-panel-content/properties-panel-content/DetailsPane.tsx
  packages/nexusgraph-graph/src/inspection-panel/properties-panel-content/properties-panel-content/OverviewPane.tsx
  packages/nexusgraph-graph/src/inspection-panel/properties-panel-content/properties-panel-content/StyleableNodeLabel.tsx
  packages/nexusgraph-graph/src/inspection-panel/properties-panel-content/properties-panel-content/StyleableRelType.tsx
  yarn.lock
Labels: MERGEABLE

#108 Add test for connecting editor and graphing via Redux
  packages/nexusgraph-app/src/index.tsx
  packages/nexusgraph-editor/src/Lexical/plugins/NexusgraphOnChangePlugin.test.tsx
  packages/nexusgraph-editor/src/Lexical/plugins/NexusgraphOnChangePlugin.tsx
  packages/nexusgraph-editor/src/Lexical/processor/NaturalLanguageProcessor.ts
  packages/nexusgraph-editor/src/Lexical/processor/RemoteNaturalLanguageProcessor.test.ts
  packages/nexusgraph-editor/src/Lexical/processor/RemoteNaturalLanguageProcessor.ts
  packages/nexusgraph-graph/src/Graph.tsx
  packages/nexusgraph-graph/src/shared/editor/editorDuck.ts
Labels: MERGEABLE, EDITOR

#109 Implement Node Expansion
  packages/nexusgraph-editor/src/Editor.test.tsx
  packages/nexusgraph-editor/src/Lexical/LexicalEditor.test.tsx
  packages/nexusgraph-editor/src/Lexical/plugins/NexusgraphOnChangePlugin.tsx
  packages/nexusgraph-editor/src/Lexical/processor/RemoteNaturalLanguageProcessor.ts
  packages/nexusgraph-graph/index.ts
  packages/nexusgraph-graph/src/GraphGeometryModel.ts
  packages/nexusgraph-graph/src/GraphVisualizer.tsx
  packages/nexusgraph-graph/src/event-handler/GraphEventHandlerModel.ts
  packages/nexusgraph-graph/src/inspection-panel/properties-panel-content/properties-panel-content/OverviewPane.tsx
  packages/nexusgraph-graph/src/processor/NodesExpand.ts
Labels: MERGEABLE

#112 App Style Customization
  docs/static/img/app-logo.ai
  packages/nexusgraph-app/public/app-logo.png
  packages/nexusgraph-app/src/App.tsx
  packages/nexusgraph-app/src/styled.ts
  packages/nexusgraph-editor/src/Lexical/LexicalEditor.module.css
  packages/nexusgraph-editor/src/Lexical/LexicalEditor.tsx
  packages/nexusgraph-editor/src/Lexical/processor/RemoteNaturalLanguageProcessor.test.ts
  packages/nexusgraph-editor/src/Lexical/processor/RemoteNaturalLanguageProcessor.ts
  packages/nexusgraph-graph/src/GraphStyle.ts
  packages/nexusgraph-graph/src/VisualizationView.styled.tsx
  packages/nexusgraph-graph/src/processor/NodesExpand.ts
  packages/nexusgraph-graph/src/styles/DefaultPane.styled.ts
  packages/nexusgraph-graph/src/styles/InspectorContainer.styled.ts
Labels: MERGEABLE, GRAPH

#113 Backpressuring Theresa requests
  packages/nexusgraph-editor/src/Lexical/plugins/NexusgraphOnChangePlugin.tsx
Labels: MERGEABLE, EDITOR

#115 Externalize Configuration
  .github/workflows/ci-cd.yml
  .gitignore
  config/webpack/webpack.config.js
  config/webpack/webpackDevServer.config.js
  docs/docs/development/architecture.md
  docs/docs/development/configuration.md
  hashicorp/scripts/setup-landing-page.sh
  package.json
  packages/nexusgraph-editor/src/Lexical/plugins/NexusgraphOnChangePlugin.tsx
  packages/nexusgraph-editor/src/Lexical/processor/RemoteNaturalLanguageProcessor.test.ts
  packages/nexusgraph-editor/src/Lexical/processor/RemoteNaturalLanguageProcessor.ts
  packages/nexusgraph-graph/src/processor/NodesExpand.ts
  scripts/start.js
  yarn.lock
Labels: CI/CD, MERGEABLE

#117 Use bracket notation to avoid false-negative type checking at compile time
  packages/nexusgraph-editor/src/Lexical/processor/RemoteNaturalLanguageProcessor.test.ts
Labels: MERGEABLE, REFACTOR

#119 Removing import React from "react"
  packages/nexusgraph-app/src/index.tsx
  packages/nexusgraph-editor/src/Editor.tsx
  packages/nexusgraph-editor/src/Lexical/LexicalEditor.tsx
  packages/nexusgraph-graph/src/Graph.tsx
  packages/nexusgraph-graph/src/GraphVisualizer.tsx
  packages/nexusgraph-graph/src/VisualizationView.tsx
  packages/nexusgraph-graph/src/WheelZoomInfoOverlay.tsx
  packages/nexusgraph-graph/src/inspection-panel/ClickableUrls.tsx
  packages/nexusgraph-graph/src/inspection-panel/ClipboardCopier.tsx
  packages/nexusgraph-graph/src/inspection-panel/DefaultDetailsPane.tsx
  packages/nexusgraph-graph/src/inspection-panel/DefaultOverviewPane.tsx
  packages/nexusgraph-graph/src/inspection-panel/NodeInspectorDrawer.tsx
  packages/nexusgraph-graph/src/inspection-panel/NodeInspectorPanel.tsx
  packages/nexusgraph-graph/src/inspection-panel/NodeLabel.tsx
  packages/nexusgraph-graph/src/inspection-panel/PropertiesTable.tsx
  packages/nexusgraph-graph/src/inspection-panel/RelType.tsx
  packages/nexusgraph-graph/src/inspection-panel/ShowMoreOrAll.tsx
  packages/nexusgraph-graph/src/inspection-panel/WarningMessage.tsx
  packages/nexusgraph-graph/src/styles/themes.tsx
Labels: MERGEABLE, REFACTOR

#116 Setup e2e and add relationship type test
  .eslintrc.json
  cypress.config.ts
  cypress/e2e/spec.cy.ts
  docs/docs/development/environment.md
  package.json
  packages/nexusgraph-editor/src/Lexical/processor/RemoteNaturalLanguageProcessor.ts
  packages/nexusgraph-graph/index.ts
  packages/nexusgraph-graph/src/ArcArrow.test.ts
  packages/nexusgraph-graph/src/GraphStats.ts
  packages/nexusgraph-graph/src/PairwiseArcsRelationshipRouting.ts
  packages/nexusgraph-graph/src/StraightArrow.test.ts
  packages/nexusgraph-graph/src/processor/NodesExpand.ts
  yarn.lock
Labels: MERGEABLE, GRAPH

#122 Load environment variable file into IAM
  .github/workflows/ci-cd.yml
  hashicorp/images/aws-nexusgraph-app.pkr.hcl
  hashicorp/scripts/setup-app.sh
Labels: BUG, CI/CD, MERGEABLE

#120 Add nexusgraph basic e2e test
  .github/workflows/ci-cd.yml
  .gitignore
  cypress.config.ts
  cypress/e2e/nexusgraph.spec.cy.ts
  cypress/e2e/spec.cy.ts
  cypress/fixtures/getEditorData.json
  cypress/fixtures/nodeExpandData.json
  docs/docs/development/environment.md
  package.json
  scripts/start.js
  scripts/wait-on-config.js
  yarn.lock
Labels: NEED 1 REVIEW, NEED CHANGES

#123 Support capturing entire editing area contents for Theresa analysis
  packages/nexusgraph-editor/src/Lexical/parser/LexicalEditorStateParser.test.ts
  packages/nexusgraph-editor/src/Lexical/parser/LexicalEditorStateParser.ts
  packages/nexusgraph-editor/src/Lexical/parser/RawTextParser.test.ts
  packages/nexusgraph-editor/src/Lexical/parser/RawTextParser.ts
  packages/nexusgraph-editor/src/Lexical/parser/index.ts
  packages/nexusgraph-editor/src/Lexical/parser/json/LexicalEditorStateParser-basic.json
  packages/nexusgraph-editor/src/Lexical/parser/json/LexicalEditorStateParser-parseLine-basic.json
  packages/nexusgraph-editor/src/Lexical/parser/json/LexicalEditorStateParser-with-empty-line.json
  packages/nexusgraph-editor/src/Lexical/plugins/NexusgraphOnChangePlugin.tsx
Labels: BUG, NEED 1 REVIEW, EDITOR

#124 Node Text Position Ddebug
  cypress/e2e/nexusgraph.spec.cy.ts
  packages/nexusgraph-editor/src/Lexical/processor/RemoteNaturalLanguageProcessor.test.ts
  packages/nexusgraph-editor/src/Lexical/processor/RemoteNaturalLanguageProcessor.ts
  packages/nexusgraph-graph/src/GraphGeometryModel.ts
Labels: MERGEABLE

#125 App changed to chinese theme
  packages/nexusgraph-app/src/App.tsx
  packages/nexusgraph-app/src/styled.ts
  packages/nexusgraph-graph/src/GraphStyle.ts
  packages/nexusgraph-graph/src/inspection-panel/DefaultDetailsPane.tsx
  packages/nexusgraph-graph/src/inspection-panel/DefaultOverviewPane.tsx
  packages/nexusgraph-graph/src/inspection-panel/NodeInspectorPanel.tsx
  packages/nexusgraph-graph/src/inspection-panel/properties-panel-content/properties-panel-content/DetailsPane.tsx
  packages/nexusgraph-graph/src/inspection-panel/properties-panel-content/properties-panel-content/OverviewPane.tsx
Labels: MERGEABLE

#121 Fix 'all nodes (*) count is always 0 at initial rendering' issue
  cypress/e2e/NodeInspectorPanel.spec.cy.ts
  cypress/fixtures/single-rdf-pair-graph.json
  packages/nexusgraph-graph/src/GraphVisualizer.tsx
  packages/nexusgraph-graph/src/inspection-panel/NodeInspectorPanel.tsx
Labels: MERGEABLE

#126 Support Doc in both Chinese and English
  docs/README.md
  docs/docusaurus.config.js
  docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/development/_category_.json
  docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/development/architecture.md
  docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/development/img/nexusgraph-architecture.drawio
  docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/development/img/nexusgraph-architecture.png
  docs/src/pages/index.tsx
  packages/nexusgraph-app/src/App.tsx
  packages/nexusgraph-graph/src/GraphBrowser.tsx
Labels: DOCUMENTATION, MERGEABLE

#129 Comment panel warning
  packages/nexusgraph-graph/src/GraphVisualizer.tsx
Labels: BUG, MERGEABLE

#128 Integrate Prometheus caching service
  cypress/e2e/NodeInspectorPanel.spec.cy.ts
  cypress/e2e/nexusgraph.spec.cy.ts
  packages/nexusgraph-editor/src/Lexical/processor/RemoteNaturalLanguageProcessor.test.ts
  packages/nexusgraph-editor/src/Lexical/processor/RemoteNaturalLanguageProcessor.ts
  packages/nexusgraph-graph/src/processor/NodesExpand.ts
Labels: MERGEABLE, GRAPH, NEW FEATURE

#130 Add expand processor test
  cypress/e2e/NodeInspectorPanel.spec.cy.ts
  packages/nexusgraph-graph/src/processor/NodesExpand.test.ts
  packages/nexusgraph-graph/src/processor/NodesExpand.ts
Labels: MERGEABLE

#114 implement-editor-toolbar day3
  config/webpack/webpack.config.js
  packages/nexusgraph-editor/src/Editor.tsx
  packages/nexusgraph-editor/src/Lexical/LexicalEditor.module.css
  packages/nexusgraph-editor/src/Lexical/LexicalEditor.tsx
  packages/nexusgraph-editor/src/Lexical/LexicalEditorConfig.ts
  packages/nexusgraph-editor/src/Lexical/plugins/CodeHighlightPlugin.js
  packages/nexusgraph-editor/src/Lexical/plugins/ToolbarPlugin.js
  packages/nexusgraph-editor/src/Lexical/plugins/ToolbarPlugin.test.tsx
  packages/nexusgraph-editor/src/Lexical/plugins/styled.ts
  packages/nexusgraph-editor/src/Lexical/themes/ExampleTheme.js
Labels: MERGEABLE, EDITOR

#131 Fix editor out-of-screen issue
  packages/nexusgraph-app/src/styled.ts
  packages/nexusgraph-editor/src/Lexical/LexicalEditor.module.css
Labels: MERGEABLE, EDITOR

#134 editor-optimization
  cypress/e2e/editor.spec.cy.ts
  packages/nexusgraph-editor/src/Lexical/plugins/NexusgraphOnChangePlugin.tsx
  packages/nexusgraph-editor/src/Lexical/plugins/ToolbarPlugin.js
  packages/nexusgraph-editor/src/Lexical/plugins/styled.ts
Labels: NEED 1 REVIEW

#135 NLP Refactoring
  packages/nexusgraph-app/src/App.tsx
  packages/nexusgraph-editor/src/Lexical/plugins/NexusgraphOnChangePlugin.test.tsx
  packages/nexusgraph-editor/src/Lexical/plugins/NexusgraphOnChangePlugin.tsx
  packages/nexusgraph-graph/src/VisualizationView.tsx
  packages/nexusgraph-nlp/src/processor/NaturalLanguageProcessor.ts
  packages/nexusgraph-nlp/src/processor/RemoteNaturalLanguageProcessor.test.ts
  packages/nexusgraph-nlp/src/processor/RemoteNaturalLanguageProcessor.ts
  packages/nexusgraph-provider/index.ts
  packages/nexusgraph-provider/src/shared/editorLine/editorLineDuck.ts
  packages/nexusgraph-provider/src/shared/globalState.ts
  packages/nexusgraph-provider/src/shared/nlp/nlpDuck.ts
  packages/nexusgraph-provider/src/shared/rootReducer.ts
Labels: MERGEABLE

#136 Toolbar plugin js change to ts
  cypress/e2e/editor.spec.cy.ts
  packages/nexusgraph-editor/src/Lexical/plugins/CodeHighlightPlugin.tsx
  packages/nexusgraph-editor/src/Lexical/plugins/ToolbarPlugin.tsx
Labels: MERGEABLE

#140 Do not send logs to sentry.io in the local development
  .github/workflows/ci-cd.yml
  config/webpack/webpack.config.js
  packages/nexusgraph-app/src/index.tsx
Labels: MERGEABLE

#139 Write editor scrollbar stuck problem document
  docs/docs/development/_category_.json
  docs/docs/development/img/editor-scrollbar-stuck-issue.png
  docs/docs/development/img/open-general-settings.png
  docs/docs/development/img/scrollbar-automatically.png
  docs/docs/development/img/scrollbar-when-scrolling.png
  docs/docs/troubleshooting.md
  docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/development/environment.md
  docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/development/img/open-general-settings.png
  docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/development/img/scrollbar-automatically.png
  docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/development/img/scrollbar-when-scrolling.png
  docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/troubleshooting.md
Labels: MERGEABLE
